services:

  hiddify:
    image: ghcr.io/hiddify/hiddify-manager:latest
    container_name: hiddify
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REDIS_URI_SSH=redis://hiddify-redis:6379
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DB=hiddify
      - MYSQL_HOST=hiddify-db
    volumes:
      - ./hiddify:/opt/hiddify-manager
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    container_name: hiddify-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: hiddify
    volumes:
      - ./hiddify/mariadb:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: hiddify-redis
    restart: always
    volumes:
      - ./hiddify/redis:/data

  mtproxy:
    image: seriyps/mtproto-proxy:latest
    container_name: mtproxy
    restart: always
    ports:
      - "8443:443"
    volumes:
      - ./mtproxy/data:/data
      - ./mtproxy/logs:/var/log/mtproxy

  vpn-bot:
    build: ./vpn-bot
    container_name: vpn-bot
    restart: always
    volumes:
      - ./vpn-bot/data:/app/data
      - ./mtproxy/logs:/mtproxy/logs:ro
      - ./mtproxy/data:/mtproxy/data
    env_file:
      - .env
    depends_on:
      - hiddify
      - mtproxy
